# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from pyost.rpc.pb import rpc_pb2 as rpc_dot_pb_dot_rpc__pb2


class ApiServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetNodeInfo = channel.unary_unary(
        '/rpcpb.ApiService/GetNodeInfo',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.EmptyRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.NodeInfoResponse.FromString,
        )
    self.GetChainInfo = channel.unary_unary(
        '/rpcpb.ApiService/GetChainInfo',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.EmptyRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.ChainInfoResponse.FromString,
        )
    self.GetRAMInfo = channel.unary_unary(
        '/rpcpb.ApiService/GetRAMInfo',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.EmptyRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.RAMInfoResponse.FromString,
        )
    self.GetTxByHash = channel.unary_unary(
        '/rpcpb.ApiService/GetTxByHash',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.TxHashRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.TransactionResponse.FromString,
        )
    self.GetTxReceiptByTxHash = channel.unary_unary(
        '/rpcpb.ApiService/GetTxReceiptByTxHash',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.TxHashRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.TxReceipt.FromString,
        )
    self.GetBlockByHash = channel.unary_unary(
        '/rpcpb.ApiService/GetBlockByHash',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetBlockByHashRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.BlockResponse.FromString,
        )
    self.GetBlockByNumber = channel.unary_unary(
        '/rpcpb.ApiService/GetBlockByNumber',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetBlockByNumberRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.BlockResponse.FromString,
        )
    self.GetAccount = channel.unary_unary(
        '/rpcpb.ApiService/GetAccount',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetAccountRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.Account.FromString,
        )
    self.GetTokenBalance = channel.unary_unary(
        '/rpcpb.ApiService/GetTokenBalance',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetTokenBalanceRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.GetTokenBalanceResponse.FromString,
        )
    self.GetToken721Balance = channel.unary_unary(
        '/rpcpb.ApiService/GetToken721Balance',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetTokenBalanceRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.GetToken721BalanceResponse.FromString,
        )
    self.GetToken721Metadata = channel.unary_unary(
        '/rpcpb.ApiService/GetToken721Metadata',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetToken721InfoRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.GetToken721MetadataResponse.FromString,
        )
    self.GetToken721Owner = channel.unary_unary(
        '/rpcpb.ApiService/GetToken721Owner',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetToken721InfoRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.GetToken721OwnerResponse.FromString,
        )
    self.GetGasRatio = channel.unary_unary(
        '/rpcpb.ApiService/GetGasRatio',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.EmptyRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.GasRatioResponse.FromString,
        )
    self.GetContract = channel.unary_unary(
        '/rpcpb.ApiService/GetContract',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetContractRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.Contract.FromString,
        )
    self.GetContractStorage = channel.unary_unary(
        '/rpcpb.ApiService/GetContractStorage',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetContractStorageRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.GetContractStorageResponse.FromString,
        )
    self.GetContractStorageFields = channel.unary_unary(
        '/rpcpb.ApiService/GetContractStorageFields',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.GetContractStorageFieldsRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.GetContractStorageFieldsResponse.FromString,
        )
    self.SendTransaction = channel.unary_unary(
        '/rpcpb.ApiService/SendTransaction',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.TransactionRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.SendTransactionResponse.FromString,
        )
    self.ExecTransaction = channel.unary_unary(
        '/rpcpb.ApiService/ExecTransaction',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.TransactionRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.TxReceipt.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/rpcpb.ApiService/Subscribe',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.SubscribeResponse.FromString,
        )


class ApiServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetNodeInfo(self, request, context):
    """get the node information
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChainInfo(self, request, context):
    """get blockchain information
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRAMInfo(self, request, context):
    """get current blockchain ram information
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTxByHash(self, request, context):
    """get transaction by hash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTxReceiptByTxHash(self, request, context):
    """get transaction receipt by transaction hash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByHash(self, request, context):
    """get block by hash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByNumber(self, request, context):
    """get block by number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccount(self, request, context):
    """get account
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTokenBalance(self, request, context):
    """get token balance
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetToken721Balance(self, request, context):
    """get token721 balance
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetToken721Metadata(self, request, context):
    """get token721 metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetToken721Owner(self, request, context):
    """get token721 owner
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGasRatio(self, request, context):
    """get gas ratio infomation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetContract(self, request, context):
    """get contract
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetContractStorage(self, request, context):
    """get contract storage
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetContractStorageFields(self, request, context):
    """get contract fields storage
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendTransaction(self, request, context):
    """send transaction
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExecTransaction(self, request, context):
    """execute transaction
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    """subscribe an event
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ApiServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetNodeInfo,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.EmptyRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.NodeInfoResponse.SerializeToString,
      ),
      'GetChainInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetChainInfo,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.EmptyRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.ChainInfoResponse.SerializeToString,
      ),
      'GetRAMInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetRAMInfo,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.EmptyRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.RAMInfoResponse.SerializeToString,
      ),
      'GetTxByHash': grpc.unary_unary_rpc_method_handler(
          servicer.GetTxByHash,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.TxHashRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.TransactionResponse.SerializeToString,
      ),
      'GetTxReceiptByTxHash': grpc.unary_unary_rpc_method_handler(
          servicer.GetTxReceiptByTxHash,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.TxHashRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.TxReceipt.SerializeToString,
      ),
      'GetBlockByHash': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByHash,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetBlockByHashRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.BlockResponse.SerializeToString,
      ),
      'GetBlockByNumber': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByNumber,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetBlockByNumberRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.BlockResponse.SerializeToString,
      ),
      'GetAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccount,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetAccountRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.Account.SerializeToString,
      ),
      'GetTokenBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetTokenBalance,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetTokenBalanceRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.GetTokenBalanceResponse.SerializeToString,
      ),
      'GetToken721Balance': grpc.unary_unary_rpc_method_handler(
          servicer.GetToken721Balance,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetTokenBalanceRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.GetToken721BalanceResponse.SerializeToString,
      ),
      'GetToken721Metadata': grpc.unary_unary_rpc_method_handler(
          servicer.GetToken721Metadata,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetToken721InfoRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.GetToken721MetadataResponse.SerializeToString,
      ),
      'GetToken721Owner': grpc.unary_unary_rpc_method_handler(
          servicer.GetToken721Owner,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetToken721InfoRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.GetToken721OwnerResponse.SerializeToString,
      ),
      'GetGasRatio': grpc.unary_unary_rpc_method_handler(
          servicer.GetGasRatio,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.EmptyRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.GasRatioResponse.SerializeToString,
      ),
      'GetContract': grpc.unary_unary_rpc_method_handler(
          servicer.GetContract,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetContractRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.Contract.SerializeToString,
      ),
      'GetContractStorage': grpc.unary_unary_rpc_method_handler(
          servicer.GetContractStorage,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetContractStorageRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.GetContractStorageResponse.SerializeToString,
      ),
      'GetContractStorageFields': grpc.unary_unary_rpc_method_handler(
          servicer.GetContractStorageFields,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.GetContractStorageFieldsRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.GetContractStorageFieldsResponse.SerializeToString,
      ),
      'SendTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.SendTransaction,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.TransactionRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.SendTransactionResponse.SerializeToString,
      ),
      'ExecTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.ExecTransaction,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.TransactionRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.TxReceipt.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.SubscribeRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.SubscribeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rpcpb.ApiService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
