# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from github.com.iost_official.go_iost.rpc import apis_pb2 as github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ApisStub(object):
  """rpc apis
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetHeight = channel.unary_unary(
        '/rpc.Apis/GetHeight',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.HeightRes.FromString,
        )
    self.GetTxByHash = channel.unary_unary(
        '/rpc.Apis/GetTxByHash',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.HashReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.txRes.FromString,
        )
    self.GetTxReceiptByHash = channel.unary_unary(
        '/rpc.Apis/GetTxReceiptByHash',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.HashReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.txReceiptRes.FromString,
        )
    self.GetTxReceiptByTxHash = channel.unary_unary(
        '/rpc.Apis/GetTxReceiptByTxHash',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.HashReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.txReceiptRes.FromString,
        )
    self.GetBlockByHash = channel.unary_unary(
        '/rpc.Apis/GetBlockByHash',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.BlockByHashReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.BlockInfo.FromString,
        )
    self.getBlockByNum = channel.unary_unary(
        '/rpc.Apis/getBlockByNum',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.BlockByNumReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.BlockInfo.FromString,
        )
    self.GetBalance = channel.unary_unary(
        '/rpc.Apis/GetBalance',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetBalanceReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetBalanceRes.FromString,
        )
    self.GetNetID = channel.unary_unary(
        '/rpc.Apis/GetNetID',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetNetIDRes.FromString,
        )
    self.GetState = channel.unary_unary(
        '/rpc.Apis/GetState',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetStateReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetStateRes.FromString,
        )
    self.SendRawTx = channel.unary_unary(
        '/rpc.Apis/SendRawTx',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.RawTxReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.SendRawTxRes.FromString,
        )
    self.EstimateGas = channel.unary_unary(
        '/rpc.Apis/EstimateGas',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.RawTxReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GasRes.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/rpc.Apis/Subscribe',
        request_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.SubscribeReq.SerializeToString,
        response_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.SubscribeRes.FromString,
        )


class ApisServicer(object):
  """rpc apis
  """

  def GetHeight(self, request, context):
    """get the current height of the blockchain
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTxByHash(self, request, context):
    """get the tx by hash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTxReceiptByHash(self, request, context):
    """get receipt by hash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTxReceiptByTxHash(self, request, context):
    """get receipt by txhash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockByHash(self, request, context):
    """get the block by hash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getBlockByNum(self, request, context):
    """get the block by number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBalance(self, request, context):
    """get the balance of some account by account ID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNetID(self, request, context):
    """get the Net ID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetState(self, request, context):
    """get the value of the corresponding key in stateDB
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendRawTx(self, request, context):
    """receive encoded tx
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EstimateGas(self, request, context):
    """not supported yet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    """subscribe an event
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ApisServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetHeight': grpc.unary_unary_rpc_method_handler(
          servicer.GetHeight,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.HeightRes.SerializeToString,
      ),
      'GetTxByHash': grpc.unary_unary_rpc_method_handler(
          servicer.GetTxByHash,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.HashReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.txRes.SerializeToString,
      ),
      'GetTxReceiptByHash': grpc.unary_unary_rpc_method_handler(
          servicer.GetTxReceiptByHash,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.HashReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.txReceiptRes.SerializeToString,
      ),
      'GetTxReceiptByTxHash': grpc.unary_unary_rpc_method_handler(
          servicer.GetTxReceiptByTxHash,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.HashReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.txReceiptRes.SerializeToString,
      ),
      'GetBlockByHash': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockByHash,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.BlockByHashReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.BlockInfo.SerializeToString,
      ),
      'getBlockByNum': grpc.unary_unary_rpc_method_handler(
          servicer.getBlockByNum,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.BlockByNumReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.BlockInfo.SerializeToString,
      ),
      'GetBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetBalance,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetBalanceReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetBalanceRes.SerializeToString,
      ),
      'GetNetID': grpc.unary_unary_rpc_method_handler(
          servicer.GetNetID,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetNetIDRes.SerializeToString,
      ),
      'GetState': grpc.unary_unary_rpc_method_handler(
          servicer.GetState,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetStateReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GetStateRes.SerializeToString,
      ),
      'SendRawTx': grpc.unary_unary_rpc_method_handler(
          servicer.SendRawTx,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.RawTxReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.SendRawTxRes.SerializeToString,
      ),
      'EstimateGas': grpc.unary_unary_rpc_method_handler(
          servicer.EstimateGas,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.RawTxReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.GasRes.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.SubscribeReq.FromString,
          response_serializer=github_dot_com_dot_iost__official_dot_go__iost_dot_rpc_dot_apis__pb2.SubscribeRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rpc.Apis', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
