# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crypto/signature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crypto/signature.proto',
  package='crypto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63rypto/signature.proto\x12\x06\x63rypto\">\n\x0cSignatureRaw\x12\x11\n\talgorithm\x18\x01 \x01(\x05\x12\x0b\n\x03sig\x18\x02 \x01(\x0c\x12\x0e\n\x06pubKey\x18\x03 \x01(\x0c\x62\x06proto3')
)




_SIGNATURERAW = _descriptor.Descriptor(
  name='SignatureRaw',
  full_name='crypto.SignatureRaw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='crypto.SignatureRaw.algorithm', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sig', full_name='crypto.SignatureRaw.sig', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pubKey', full_name='crypto.SignatureRaw.pubKey', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['SignatureRaw'] = _SIGNATURERAW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignatureRaw = _reflection.GeneratedProtocolMessageType('SignatureRaw', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATURERAW,
  __module__ = 'crypto.signature_pb2'
  # @@protoc_insertion_point(class_scope:crypto.SignatureRaw)
  ))
_sym_db.RegisterMessage(SignatureRaw)


# @@protoc_insertion_point(module_scope)
