# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/iost-official/go-iost/core/block/block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.com/iost-official/go-iost/core/block/block.proto',
  package='block',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n7github.com/iost-official/go-iost/core/block/block.proto\x12\x05\x62lock\"\x92\x01\n\tBlockHead\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x12\n\nparentHash\x18\x02 \x01(\x0c\x12\x0f\n\x07txsHash\x18\x03 \x01(\x0c\x12\x12\n\nmerkleHash\x18\x04 \x01(\x0c\x12\x0c\n\x04info\x18\x05 \x01(\x0c\x12\x0e\n\x06number\x18\x06 \x01(\x03\x12\x0f\n\x07witness\x18\x07 \x01(\t\x12\x0c\n\x04time\x18\x08 \x01(\x03\"W\n\x08\x42lockRaw\x12\x1e\n\x04head\x18\x01 \x01(\x0b\x32\x10.block.BlockHead\x12\x0c\n\x04sign\x18\x02 \x01(\x0c\x12\x0b\n\x03txs\x18\x03 \x03(\x0c\x12\x10\n\x08receipts\x18\x04 \x03(\x0c\x62\x06proto3')
)




_BLOCKHEAD = _descriptor.Descriptor(
  name='BlockHead',
  full_name='block.BlockHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='block.BlockHead.version', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parentHash', full_name='block.BlockHead.parentHash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txsHash', full_name='block.BlockHead.txsHash', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merkleHash', full_name='block.BlockHead.merkleHash', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='block.BlockHead.info', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='block.BlockHead.number', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='witness', full_name='block.BlockHead.witness', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='block.BlockHead.time', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=213,
)


_BLOCKRAW = _descriptor.Descriptor(
  name='BlockRaw',
  full_name='block.BlockRaw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='head', full_name='block.BlockRaw.head', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign', full_name='block.BlockRaw.sign', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txs', full_name='block.BlockRaw.txs', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receipts', full_name='block.BlockRaw.receipts', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=302,
)

_BLOCKRAW.fields_by_name['head'].message_type = _BLOCKHEAD
DESCRIPTOR.message_types_by_name['BlockHead'] = _BLOCKHEAD
DESCRIPTOR.message_types_by_name['BlockRaw'] = _BLOCKRAW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockHead = _reflection.GeneratedProtocolMessageType('BlockHead', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKHEAD,
  __module__ = 'github.com.iost_official.go_iost.core.block.block_pb2'
  # @@protoc_insertion_point(class_scope:block.BlockHead)
  ))
_sym_db.RegisterMessage(BlockHead)

BlockRaw = _reflection.GeneratedProtocolMessageType('BlockRaw', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKRAW,
  __module__ = 'github.com.iost_official.go_iost.core.block.block_pb2'
  # @@protoc_insertion_point(class_scope:block.BlockRaw)
  ))
_sym_db.RegisterMessage(BlockRaw)


# @@protoc_insertion_point(module_scope)
