# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/iost-official/go-iost/core/event/event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.com/iost-official/go-iost/core/event/event.proto',
  package='event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n7github.com/iost-official/go-iost/core/event/event.proto\x12\x05\x65vent\"\xa9\x01\n\x05\x45vent\x12!\n\x05topic\x18\x01 \x01(\x0e\x32\x12.event.Event.Topic\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\"a\n\x05Topic\x12\x15\n\x11TransactionResult\x10\x00\x12\x11\n\rContractEvent\x10\x01\x12\x15\n\x11\x43ontractUserEvent\x10\x02\x12\x17\n\x13\x43ontractSystemEvent\x10\x03\x62\x06proto3')
)



_EVENT_TOPIC = _descriptor.EnumDescriptor(
  name='Topic',
  full_name='event.Event.Topic',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TransactionResult', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ContractEvent', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ContractUserEvent', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ContractSystemEvent', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=139,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_EVENT_TOPIC)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='event.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='event.Event.topic', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='event.Event.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='event.Event.time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENT_TOPIC,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=236,
)

_EVENT.fields_by_name['topic'].enum_type = _EVENT_TOPIC
_EVENT_TOPIC.containing_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'github.com.iost_official.go_iost.core.event.event_pb2'
  # @@protoc_insertion_point(class_scope:event.Event)
  ))
_sym_db.RegisterMessage(Event)


# @@protoc_insertion_point(module_scope)
