# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/iost-official/go-iost/p2p/pb/message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.com/iost-official/go-iost/p2p/pb/message.proto',
  package='p2pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n5github.com/iost-official/go-iost/p2p/pb/message.proto\x12\x04p2pb\"\x1b\n\x0cRoutingQuery\x12\x0b\n\x03ids\x18\x01 \x03(\t\"%\n\x08PeerInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x61\x64\x64rs\x18\x02 \x03(\t\"0\n\x0fRoutingResponse\x12\x1d\n\x05peers\x18\x01 \x03(\x0b\x32\x0e.p2pb.PeerInfob\x06proto3')
)




_ROUTINGQUERY = _descriptor.Descriptor(
  name='RoutingQuery',
  full_name='p2pb.RoutingQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='p2pb.RoutingQuery.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=90,
)


_PEERINFO = _descriptor.Descriptor(
  name='PeerInfo',
  full_name='p2pb.PeerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='p2pb.PeerInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addrs', full_name='p2pb.PeerInfo.addrs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=129,
)


_ROUTINGRESPONSE = _descriptor.Descriptor(
  name='RoutingResponse',
  full_name='p2pb.RoutingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peers', full_name='p2pb.RoutingResponse.peers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=179,
)

_ROUTINGRESPONSE.fields_by_name['peers'].message_type = _PEERINFO
DESCRIPTOR.message_types_by_name['RoutingQuery'] = _ROUTINGQUERY
DESCRIPTOR.message_types_by_name['PeerInfo'] = _PEERINFO
DESCRIPTOR.message_types_by_name['RoutingResponse'] = _ROUTINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoutingQuery = _reflection.GeneratedProtocolMessageType('RoutingQuery', (_message.Message,), dict(
  DESCRIPTOR = _ROUTINGQUERY,
  __module__ = 'github.com.iost_official.go_iost.p2p.pb.message_pb2'
  # @@protoc_insertion_point(class_scope:p2pb.RoutingQuery)
  ))
_sym_db.RegisterMessage(RoutingQuery)

PeerInfo = _reflection.GeneratedProtocolMessageType('PeerInfo', (_message.Message,), dict(
  DESCRIPTOR = _PEERINFO,
  __module__ = 'github.com.iost_official.go_iost.p2p.pb.message_pb2'
  # @@protoc_insertion_point(class_scope:p2pb.PeerInfo)
  ))
_sym_db.RegisterMessage(PeerInfo)

RoutingResponse = _reflection.GeneratedProtocolMessageType('RoutingResponse', (_message.Message,), dict(
  DESCRIPTOR = _ROUTINGRESPONSE,
  __module__ = 'github.com.iost_official.go_iost.p2p.pb.message_pb2'
  # @@protoc_insertion_point(class_scope:p2pb.RoutingResponse)
  ))
_sym_db.RegisterMessage(RoutingResponse)


# @@protoc_insertion_point(module_scope)
