# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/iost-official/go-iost/core/tx/tx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.iost_official.go_iost.crypto import signature_pb2 as github_dot_com_dot_iost__official_dot_go__iost_dot_crypto_dot_signature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.com/iost-official/go-iost/core/tx/tx.proto',
  package='tx',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n1github.com/iost-official/go-iost/core/tx/tx.proto\x12\x02tx\x1a\x37github.com/iost-official/go-iost/crypto/signature.proto\"?\n\tActionRaw\x12\x10\n\x08\x63ontract\x18\x01 \x01(\t\x12\x12\n\nactionName\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\xcc\x01\n\x05TxRaw\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x12\n\nexpiration\x18\x02 \x01(\x03\x12\x10\n\x08gasLimit\x18\x03 \x01(\x03\x12\x10\n\x08gasPrice\x18\x04 \x01(\x03\x12\x1e\n\x07\x61\x63tions\x18\x05 \x03(\x0b\x32\r.tx.ActionRaw\x12\x0f\n\x07signers\x18\x06 \x03(\x0c\x12#\n\x05signs\x18\x07 \x03(\x0b\x32\x14.crypto.SignatureRaw\x12\'\n\tpublisher\x18\x08 \x01(\x0b\x32\x14.crypto.SignatureRaw\"+\n\nReceiptRaw\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"*\n\tStatusRaw\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x88\x01\n\x0cTxReceiptRaw\x12\x0e\n\x06txHash\x18\x01 \x01(\x0c\x12\x10\n\x08gasUsage\x18\x02 \x01(\x03\x12\x1d\n\x06status\x18\x03 \x01(\x0b\x32\r.tx.StatusRaw\x12\x15\n\rsuccActionNum\x18\x04 \x01(\x05\x12 \n\x08receipts\x18\x05 \x03(\x0b\x32\x0e.tx.ReceiptRawb\x06proto3')
  ,
  dependencies=[github_dot_com_dot_iost__official_dot_go__iost_dot_crypto_dot_signature__pb2.DESCRIPTOR,])




_ACTIONRAW = _descriptor.Descriptor(
  name='ActionRaw',
  full_name='tx.ActionRaw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract', full_name='tx.ActionRaw.contract', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionName', full_name='tx.ActionRaw.actionName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='tx.ActionRaw.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=177,
)


_TXRAW = _descriptor.Descriptor(
  name='TxRaw',
  full_name='tx.TxRaw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='tx.TxRaw.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiration', full_name='tx.TxRaw.expiration', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gasLimit', full_name='tx.TxRaw.gasLimit', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gasPrice', full_name='tx.TxRaw.gasPrice', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions', full_name='tx.TxRaw.actions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signers', full_name='tx.TxRaw.signers', index=5,
      number=6, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signs', full_name='tx.TxRaw.signs', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publisher', full_name='tx.TxRaw.publisher', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=384,
)


_RECEIPTRAW = _descriptor.Descriptor(
  name='ReceiptRaw',
  full_name='tx.ReceiptRaw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='tx.ReceiptRaw.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='tx.ReceiptRaw.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=429,
)


_STATUSRAW = _descriptor.Descriptor(
  name='StatusRaw',
  full_name='tx.StatusRaw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='tx.StatusRaw.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='tx.StatusRaw.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=473,
)


_TXRECEIPTRAW = _descriptor.Descriptor(
  name='TxReceiptRaw',
  full_name='tx.TxReceiptRaw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txHash', full_name='tx.TxReceiptRaw.txHash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gasUsage', full_name='tx.TxReceiptRaw.gasUsage', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='tx.TxReceiptRaw.status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='succActionNum', full_name='tx.TxReceiptRaw.succActionNum', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receipts', full_name='tx.TxReceiptRaw.receipts', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=612,
)

_TXRAW.fields_by_name['actions'].message_type = _ACTIONRAW
_TXRAW.fields_by_name['signs'].message_type = github_dot_com_dot_iost__official_dot_go__iost_dot_crypto_dot_signature__pb2._SIGNATURERAW
_TXRAW.fields_by_name['publisher'].message_type = github_dot_com_dot_iost__official_dot_go__iost_dot_crypto_dot_signature__pb2._SIGNATURERAW
_TXRECEIPTRAW.fields_by_name['status'].message_type = _STATUSRAW
_TXRECEIPTRAW.fields_by_name['receipts'].message_type = _RECEIPTRAW
DESCRIPTOR.message_types_by_name['ActionRaw'] = _ACTIONRAW
DESCRIPTOR.message_types_by_name['TxRaw'] = _TXRAW
DESCRIPTOR.message_types_by_name['ReceiptRaw'] = _RECEIPTRAW
DESCRIPTOR.message_types_by_name['StatusRaw'] = _STATUSRAW
DESCRIPTOR.message_types_by_name['TxReceiptRaw'] = _TXRECEIPTRAW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionRaw = _reflection.GeneratedProtocolMessageType('ActionRaw', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONRAW,
  __module__ = 'github.com.iost_official.go_iost.core.tx.tx_pb2'
  # @@protoc_insertion_point(class_scope:tx.ActionRaw)
  ))
_sym_db.RegisterMessage(ActionRaw)

TxRaw = _reflection.GeneratedProtocolMessageType('TxRaw', (_message.Message,), dict(
  DESCRIPTOR = _TXRAW,
  __module__ = 'github.com.iost_official.go_iost.core.tx.tx_pb2'
  # @@protoc_insertion_point(class_scope:tx.TxRaw)
  ))
_sym_db.RegisterMessage(TxRaw)

ReceiptRaw = _reflection.GeneratedProtocolMessageType('ReceiptRaw', (_message.Message,), dict(
  DESCRIPTOR = _RECEIPTRAW,
  __module__ = 'github.com.iost_official.go_iost.core.tx.tx_pb2'
  # @@protoc_insertion_point(class_scope:tx.ReceiptRaw)
  ))
_sym_db.RegisterMessage(ReceiptRaw)

StatusRaw = _reflection.GeneratedProtocolMessageType('StatusRaw', (_message.Message,), dict(
  DESCRIPTOR = _STATUSRAW,
  __module__ = 'github.com.iost_official.go_iost.core.tx.tx_pb2'
  # @@protoc_insertion_point(class_scope:tx.StatusRaw)
  ))
_sym_db.RegisterMessage(StatusRaw)

TxReceiptRaw = _reflection.GeneratedProtocolMessageType('TxReceiptRaw', (_message.Message,), dict(
  DESCRIPTOR = _TXRECEIPTRAW,
  __module__ = 'github.com.iost_official.go_iost.core.tx.tx_pb2'
  # @@protoc_insertion_point(class_scope:tx.TxReceiptRaw)
  ))
_sym_db.RegisterMessage(TxReceiptRaw)


# @@protoc_insertion_point(module_scope)
